// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import EventFormController from "./event_form_controller"

application.register("event-form", EventFormController)
application.register("hello", HelloController)
